language: python
python:
  - 3.7
  - 3.9
install:
  - pip install -r requirements-dev.txt
  - pip install -q pipenv codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov