language: python
python:
  - 3.8
install:
  - pip install -q -r requirements-dev.txt codecov
  - pipenv sync --dev
script:
  - flake8
  - pytest libpythonpro --cov=libpythonpro
after_success:
  - codecov