language: python
python:
  - 3.8.5
install:
 # - pip install -q pipenv codecov
#  - pipenv sync --dev
  - pip install -q -r requirements-dev.txt
script:
  - flake8
 - pytest libpythonproal # --cov=libpythonproal

after_success:
  - codecov
